### ISSUE TITLE
Reference file upload parameter

### ISSUE THREAD

**Issue by nsuidak** [ExperienceOne/apikit#4]
I am implementing a file upload endpoint by sending a file over `multipart/form-data`. 

I defined the following parameter:
```yaml
fileParam:
    type: file
    name: file
    description: File to be uploaded in request.
    in: formData
```

I then referenced it in my endpoint definition as follows:

```yaml
post:
     consumes:
        - multipart/form-data
      parameters:
        - $ref: '#/parameters/fileParam'
     ..........
```

The implementation above throws a panic error: `invalid memory address or nil pointer dereference`. It only works when I do not reference `fileParam` and place it inline with my endpoint definition. 

Please let me know if I am missing something.

Thanks in advance :)
